<testsuites>
  <testsuite name="Reporter.Tests.dll" tests="2" skipped="0" failures="1" errors="0" time="0.091601" timestamp="2023-09-10T11:07:57" hostname="tihonove-lt-linux" id="0" package="Reporter.Tests.dll">
    <properties />
    <testcase classname="Reporter.Tests.Class1" name="Test01" time="0.0838750" />
    <testcase classname="Reporter.Tests.Class1" name="Test02" time="0.0077260">
      <failure type="failure" message="System.Exception : !!!!">at Reporter.Tests.Class1.Test02() in /home/tihonove/workspace/test-analytics/Reporter.Tests/Class1.cs:line 21
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.&lt;&gt;c__DisplayClass4_0.&lt;PerformWork&gt;b__0()
   at NUnit.Framework.Internal.ContextUtils.&lt;&gt;c__DisplayClass1_0`1.&lt;DoIsolated&gt;b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()</failure>
    </testcase>
    <system-out>
Test Framework Informational Messages:
NUnit Adapter 4.5.0.0: Test execution started
Running all tests in /home/tihonove/workspace/test-analytics/Reporter.Tests/bin/Debug/net7.0/Reporter.Tests.dll
   NUnit3TestExecutor discovered 2 of 2 NUnit test cases using Current Discovery mode, Non-Explicit run
NUnit Adapter 4.5.0.0: Test execution complete
</system-out>
    <system-err></system-err>
  </testsuite>
</testsuites>